
name: iOS UI Test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: macOS

    steps:
      - uses: actions/checkout@v2

      - name: Set up Xcode
        uses: actions/setup-xcode@v1
        with:
          xcode-version: 13.4
          osx-image: macos-12.3

      - name: Install CocoaPods
        run: gem install cocoapods

      - name: Install pods
        run: pod install

      - name: Run UI Tests
        run: xcodebuild test -scheme MyApp -destination 'platform=iOS Simulator,name=iPhone 13'
